#!/usr/bin/env python3
"""Analyze whether the 8-tag Thought Anchors taxonomy transfers from math to logic.

This script reads analysis_results.json files generated by analyze_rollouts.py and
produces transfer diagnostics:
- closed-set coverage (8 base tags + unknown fallback)
- unknown / out-of-vocabulary (OOV) rates
- multi-tag behavior
- per-tag frequency and mean counterfactual importance
- logic-operation proxy diagnostics to detect potential overload of base tags
"""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter, defaultdict
from pathlib import Path
from statistics import mean
from typing import Any


BASE_TAGS = {
    "problem_setup",
    "plan_generation",
    "fact_retrieval",
    "active_computation",
    "result_consolidation",
    "uncertainty_management",
    "final_answer_emission",
    "self_checking",
}
ALLOWED_TAGS = BASE_TAGS | {"unknown"}


LOGIC_PROXY_PATTERNS = {
    "quantifier_or_rule_application": re.compile(
        r"\b(for all|forall|there exists|exists|contrapositive|premise|implies|therefore)\b|→|->",
        re.IGNORECASE,
    ),
    "assumption_or_contradiction_management": re.compile(
        r"\b(assume|suppose|contradiction|counterexample|can't be right|cannot be right|might be making a mistake)\b",
        re.IGNORECASE,
    ),
    "case_split_or_branching": re.compile(
        r"\b(either|or|case|alternatively|another approach|if\s+.*\s+then)\b",
        re.IGNORECASE,
    ),
}


def load_labeled_chunks(path: Path) -> list[dict[str, Any]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list) or not data:
        raise ValueError(f"Unexpected format in {path}")
    return data[0]["labeled_chunks"]


def normalize_tags(raw_tags: Any) -> list[str]:
    if not isinstance(raw_tags, list):
        return ["unknown"]
    tags: list[str] = []
    for tag in raw_tags:
        if isinstance(tag, str):
            tags.append(tag.strip().lower())
    return tags if tags else ["unknown"]


def safe_mean(values: list[float]) -> float:
    return mean(values) if values else 0.0


def analyze_chunks(chunks: list[dict[str, Any]]) -> dict[str, Any]:
    total = len(chunks)
    tag_occ = Counter()
    per_tag_cfkl: dict[str, list[float]] = defaultdict(list)

    unknown_chunk_count = 0
    oov_chunk_count = 0
    multi_tag_chunk_count = 0
    base_covered_chunk_count = 0
    oov_tags = Counter()

    for chunk in chunks:
        tags = normalize_tags(chunk.get("function_tags", []))
        unique_tags = set(tags)

        if len(unique_tags) > 1:
            multi_tag_chunk_count += 1
        if "unknown" in unique_tags:
            unknown_chunk_count += 1

        in_base = unique_tags & BASE_TAGS
        if in_base:
            base_covered_chunk_count += 1

        current_oov = [t for t in unique_tags if t not in ALLOWED_TAGS]
        if current_oov:
            oov_chunk_count += 1
            oov_tags.update(current_oov)

        cf_kl = float(chunk.get("counterfactual_importance_kl", 0.0))
        for tag in unique_tags:
            tag_occ[tag] += 1
            per_tag_cfkl[tag].append(cf_kl)

    tag_stats = []
    for tag, count in tag_occ.items():
        tag_stats.append(
            {
                "tag": tag,
                "count": count,
                "chunk_ratio": count / total if total else 0.0,
                "mean_cf_kl": safe_mean(per_tag_cfkl[tag]),
            }
        )
    tag_stats.sort(key=lambda x: x["count"], reverse=True)

    return {
        "num_chunks": total,
        "base_tag_covered_chunks": base_covered_chunk_count,
        "base_tag_coverage_rate": (base_covered_chunk_count / total if total else 0.0),
        "unknown_chunk_count": unknown_chunk_count,
        "unknown_chunk_rate": (unknown_chunk_count / total if total else 0.0),
        "oov_chunk_count": oov_chunk_count,
        "oov_chunk_rate": (oov_chunk_count / total if total else 0.0),
        "oov_tags": dict(oov_tags),
        "multi_tag_chunk_count": multi_tag_chunk_count,
        "multi_tag_chunk_rate": (multi_tag_chunk_count / total if total else 0.0),
        "tags_present": sorted(tag_occ.keys()),
        "base_tags_present": sorted(t for t in tag_occ if t in BASE_TAGS),
        "tag_stats": tag_stats,
    }


def analyze_logic_proxies(chunks: list[dict[str, Any]]) -> dict[str, Any]:
    rows = []
    for chunk in chunks:
        rows.append(
            {
                "text": str(chunk.get("chunk", "")),
                "tags": normalize_tags(chunk.get("function_tags", [])),
            }
        )

    report: dict[str, Any] = {}
    total = len(rows)
    for name, pattern in LOGIC_PROXY_PATTERNS.items():
        matched = [r for r in rows if pattern.search(r["text"])]
        matched_count = len(matched)
        tag_counter = Counter()
        for r in matched:
            tag_counter.update(set(r["tags"]))

        top_tag = None
        top_share = 0.0
        if matched_count > 0 and tag_counter:
            top_tag, top_count = tag_counter.most_common(1)[0]
            top_share = top_count / matched_count

        report[name] = {
            "matched_chunks": matched_count,
            "match_rate_over_logic_chunks": (matched_count / total if total else 0.0),
            "top_tag": top_tag,
            "top_tag_share": top_share,
            "tag_counts": dict(tag_counter),
        }

    return report


def summarize_transfer(domain_stats: dict[str, Any], logic_proxy: dict[str, Any]) -> dict[str, Any]:
    logic = domain_stats["logic"]

    no_oov = logic["oov_chunk_count"] == 0
    low_unknown = logic["unknown_chunk_rate"] <= 0.02
    all_base_tags_seen = len(logic["base_tags_present"]) == 8

    recommendation = {
        "new_top_level_tag_needed": False,
        "confidence": "medium",
        "reasoning": [],
        "minimal_adaptation": [],
    }

    if not (no_oov and low_unknown):
        recommendation["new_top_level_tag_needed"] = True
        recommendation["confidence"] = "low"
        recommendation["reasoning"].append(
            "Logic chunks show non-trivial OOV/unknown rate; closed-set coverage is weak."
        )
    else:
        recommendation["reasoning"].append(
            "Logic data is almost fully covered by existing 8 tags (plus unknown fallback) with zero OOV tags."
        )

    if all_base_tags_seen:
        recommendation["reasoning"].append(
            "All 8 base tags appear in logic, supporting direct cross-domain comparability."
        )
    else:
        recommendation["reasoning"].append(
            "Not all base tags appear in current logic sample; more samples needed before taxonomy changes."
        )

    overloaded = []
    for name, stats in logic_proxy.items():
        if stats["matched_chunks"] >= 30 and stats["top_tag_share"] >= 0.70:
            overloaded.append((name, stats["top_tag"], stats["top_tag_share"]))

    if overloaded:
        recommendation["minimal_adaptation"].append(
            "Keep 8 top-level tags; add optional logic sub-tags under overloaded parent tags for fine-grained analysis."
        )
        recommendation["minimal_adaptation"].append(
            "Suggested sub-tags: quantifier_instantiation, assumption_discharge, case_split_branch, contradiction_step."
        )
    else:
        recommendation["minimal_adaptation"].append(
            "Keep the same 8 top-level tags and only add domain-specific annotation guidelines for logic."
        )
        recommendation["minimal_adaptation"].append(
            "Optional sub-tags can remain off by default and be introduced only for deeper logic-specific studies."
        )

    return recommendation


def load_setting_files(analysis_root: Path) -> dict[str, dict[str, Path]]:
    files: dict[str, dict[str, Path]] = {"math": {}, "logic": {}}
    for domain in ("math", "logic"):
        base = analysis_root / domain / "problem_0" / "im_CF_kl"
        files[domain]["correct"] = base / "correct_base_solution" / "analysis_results.json"
        files[domain]["incorrect"] = base / "incorrect_base_solution" / "analysis_results.json"
    return files


def main() -> None:
    parser = argparse.ArgumentParser(description="Taxonomy transfer diagnostics for math->logic.")
    parser.add_argument(
        "--analysis_root",
        type=Path,
        default=Path(r"D:\Files\UW-M\26_1_spring\CS639\prj\proposal_math+logic"),
        help="Root directory containing math/logic analysis outputs.",
    )
    parser.add_argument(
        "--output_json",
        type=Path,
        default=None,
        help="Optional path to save full diagnostics JSON.",
    )
    args = parser.parse_args()

    files = load_setting_files(args.analysis_root)
    chunks_by_setting: dict[str, list[dict[str, Any]]] = {}
    setting_stats: dict[str, Any] = {}
    domain_agg: dict[str, Any] = {}

    for domain in ("math", "logic"):
        all_domain_chunks: list[dict[str, Any]] = []
        for split in ("correct", "incorrect"):
            key = f"{domain}_{split}"
            path = files[domain][split]
            chunks = load_labeled_chunks(path)
            chunks_by_setting[key] = chunks
            setting_stats[key] = analyze_chunks(chunks)
            all_domain_chunks.extend(chunks)
        domain_agg[domain] = analyze_chunks(all_domain_chunks)

    logic_proxy = analyze_logic_proxies(chunks_by_setting["logic_correct"] + chunks_by_setting["logic_incorrect"])
    recommendation = summarize_transfer(domain_agg, logic_proxy)

    report = {
        "analysis_root": str(args.analysis_root),
        "base_tags": sorted(BASE_TAGS),
        "setting_stats": setting_stats,
        "domain_aggregates": domain_agg,
        "logic_proxy_diagnostics": logic_proxy,
        "recommendation": recommendation,
    }

    if args.output_json is not None:
        args.output_json.parent.mkdir(parents=True, exist_ok=True)
        args.output_json.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")

    # Human-readable summary
    print("=== Taxonomy Transfer Summary ===")
    for domain in ("math", "logic"):
        d = domain_agg[domain]
        print(
            f"{domain}: chunks={d['num_chunks']}, "
            f"base_coverage={d['base_tag_coverage_rate']:.4f}, "
            f"unknown_rate={d['unknown_chunk_rate']:.4f}, "
            f"oov_rate={d['oov_chunk_rate']:.4f}, "
            f"multi_tag_rate={d['multi_tag_chunk_rate']:.4f}, "
            f"base_tags_present={len(d['base_tags_present'])}/8"
        )

    print("\n=== Logic Proxy Diagnostics ===")
    for name, stats in logic_proxy.items():
        print(
            f"{name}: matched={stats['matched_chunks']}, "
            f"match_rate={stats['match_rate_over_logic_chunks']:.4f}, "
            f"top_tag={stats['top_tag']}, top_tag_share={stats['top_tag_share']:.4f}"
        )

    print("\n=== Recommendation ===")
    print(f"new_top_level_tag_needed={recommendation['new_top_level_tag_needed']}")
    print(f"confidence={recommendation['confidence']}")
    for line in recommendation["reasoning"]:
        print(f"- {line}")
    for line in recommendation["minimal_adaptation"]:
        print(f"- {line}")


if __name__ == "__main__":
    main()
